---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token
  namespace: external-dns
spec:
  encryptedData:
    api-token: AgAQDCohrZoMwd8NIWmaEKZLBgTgt8O084Lf6KLrwjhz9xi21FWXV3fmokuZrY404ObekkTA5Tvd2QNj8oVjtPrjJq0g03C7O6AumsXiYQPM7xyDgaIZdgfH3pwcYhX29sMyEcNSBVsbd9jfIfENUt3cyhbWCQ+CeaoUwckZJ+Bpuu0TZDRZSRF3CEfjk7CcWMxtjAGpVQOnfZRGA/MdvNt3i2En3TAUoB8krgARBq5p1ARhvJUx6SEsUzg2qEC8vVhGF/wOwuKBxQ1QAUJzxihfsfSPxlpqnRmcl3rooQxA2PO8PBvF+JQ8nxfSHlmhzBRkTMFNYq/oAXPJlRrr/UvBlx3/TX8IdsadRfmOOhanxfeUWTdJq+MkYFg0HJoGfieFU002m9cPSqjAZm9gpHYXuIIPb4eompXpEj8FQ71OrZBbwHon68XIE0WrOe/HjfHOGHEK6lD7XlAIy8K+wIXzZAI/VH88yHFw1gL+Agn3BpQoesbFbJGTS0CdohwZWKWWrkDAf4DHNKymfGquJhPSdN4KMvEOnqSltjUrMQc95ViZPGbWWq8loNvrlwhFb34kvIl6FuLQuPLakYneZElRaHQF/52pLFsVO0nTZIELCSNX/IX+7MdBp0iiG0NG3d4fIdBRwrlZOEEXR8AZ9z/DhJDLQI+fdF1nihvE0nT7DeSkNf8X+cBLoJbDfRZtY7ZGMlYdRGo4Ud04hlhBuSOCrMh9c2c6rntL8bvpr7CfjQuv5m536YR/w8AWdEA6J1kX6KG6LQ==
  template:
    metadata:
      name: cloudflare-api-token
      namespace: external-dns
