---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: alertmanager-slack
  namespace: monitoring
spec:
  encryptedData:
    bot-token: AgCWWfqKxq7FrVh8JDBXNhF4eHlcXf8vmYyw7PSpccjn5YPho4JdzHGUK3ZLzmXWBL1o2yp+pavkyYraaxxbwuzS0+2yrFUf+L+V4RK/XhwcggKuRqIWYfYnZgrh+M3EcEeOX5S7kjw6kAjDEQGQ5rM1idh62QLlQGTE9tVlfWVgLso2xZur41iv7B/LwQxZU7WzTctJKzxc/piqn39mSRb6v3FNArAeOGFCbjyjOOva0CtC2tIkHja8hQao6vL1jto30LJbvepbiuvn4+BN62EkRzkNEOhfvk83J3RPkXjC7rOdfyFGbNnWYfjRfcEbAXPjqKmPiVAvZdQOh9monS4ILGqNI6S/4HeSKeisxsokMvabIHY+IHqfZl+JOVWXzTa7yBFtMyxD73Mooyq2SF+KyC11U2nk/rRLd9BmS0lE1wjqC5RARfgVKbgL24JaBDe1b4BIrwiv4FfjM+JdOUYiYOX/iHMAnrem38zq/j1PAyjlZPKwJlhGD45Y14Z85jk2/MfM5RA+kAL8gRsiSRyX6L5BxRulPpdx9AiuHhGzbuoicdo//v/TPGoEq/2LFUmAiN0OmkTNhhN6/buwVaGqfoBcgbmy2BHfHLBBgPqGalTBpDHsUpjIH0biCwHpCYdktTi2xlLYtLoiRUaZKkrSj1ctxWUZXaJURWTBl4DC4KhfYzhGAh3oX/L6xVjEXg3I0/O/PvjwyeumbEGyvp+7ZpqwN/tGCA+mcR5YGxl0Y34W/h+KAhs0LNiRGnD7nw98FXDLgwfQoJ0o
  template:
    metadata:
      name: alertmanager-slack
      namespace: monitoring
