---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgDGWlR0SWeIQ8aV/4+q+uhLNbJZRa+K4NIawHo+rrWBC4FpaOrlP2FFn4q0AJLRsmzGw4HMbE95Pi6RJyOkLIIdB8frgDqEHxQIarijbzEYTDrTtLlKzd69lJ/cMvAExEeRddGg/kTH7tqMmEyDRRyIYEE5I+LZ7vrDVeh9P43Zf/D20ASf19DSGsk3/E8B4U0KUfhr0vP8y4VO6ANWfx5fYyiJJ2geZphLKjvGfO+ghuk5R2CeDk3NnXONbkBRt/U2uIMpSe0UGwVFtJ8c6T12gY6zLJBpu6yaew3qyFU0CgeN8DAOvW5UctCBTvUzlFWFaDKronPFv/zqPgUCOtUveTugNO6AGI7jN1BO/h3RTPcany15MX3AwC5P1sLmtoYR4eey85vuje3cn/Uq1Vw29DIpGU9PHHUdkZcL1o1sM1zfs46/bEM6SOH89tOd3ATQMzXUDopnwOgb7fq3zYL++3MifGcEngQB+RTIK/vf3SpjPAW44muMIhMCpvgOaJ9qfxL4NuVdRGgA/hlYkjeSM61+2u1wILJnegIdjVmaVvepRRC9Ue+ivhe982loCvvIjktNt4Al5RBFj5E8bhuhAK6sl/ygEV9vDt9Xarsm+cA7uCvuQhlXagURHqTjI5nwpkkr+eywB8GxKpddZ8rs6ntqV/cqoxZzz39np2khoFj9XaePoUh3dAD2UhP7s4AIanGVfWkFGEtlQHJd/Is=
    admin-user: AgCdcUaPQ8Jyyxe01Yybe4teiwKllIL2+TGPw0mbphtziPTjsu5bZk+T0yS7RYvp9S0AfsYeeIM77B8NK6120mFuhSDryZw3qwfrhBUp2He7xWYbMrPyvOfA+akwc0a924Q3AmFNXjB40sgTbPAhI/5hKbkVtIT64BMDFVfBEz7HDyCY1T1ol3SpuRhBex0bIrlj1My87youEjStdmI7toTttat19wbuTKJ/jooRqy5jkBng6jSoy2w6jp5pkkitab0jKP5foJ7xoFRRq3OJ0nPOgoQFQ/sM//mCE44pMS/oAukO2a9jGY7DWJLdMHTnj+VjwUb9xdoWGvGnMt//3wwXSlXqDNe+u0+sLnvC84it4LEQmxOZIvPPxK4+abWXTEVinywHUo0O6fPixeyVhxiYSHOY8cYMuH2zHIOHIlysjAYez6jOttu84tLgZegkBkJwI+wUTmzleZ2KdoYUvLoCgXJCKhw39RvLObpR0JnIYpGhg6CkCSnJcsV20beF4v+BYeVdDE2oZgCR6INbSbXwlQ1sAtwGUah3Z11V3fN3xcwSy3W3+0LnMlmg1EzVH2PLvgSge2MqkUXAWOIEyNqot8lHGBana7MfZ/XKNVwkKpQUakK3XJGvRa9k+nVvcht4EHyktRcSd50dqYlsUttsitYeUvUq8/Q4CxkDdb1kzmm2AyphBqp87d0JCBG/N13+aoJ/9w==
  template:
    metadata:
      name: grafana-admin
      namespace: monitoring
