---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-github
  namespace: monitoring
spec:
  encryptedData:
    GF_AUTH_GITHUB_CLIENT_ID: AgCnPPom14T02bVVrrZBxSwT1tMMJJiY+Rxz/xXoa578f/t7wkUqDI5JUTjPPKE82rjXZxgCvr84KbHmqxmObrJQ9WHquHcNENuJgMqxvaDJZTTsfjbZliyokpY0ciaoXcj0dEe2DXzDNTs3mtP8avcHFV96sYBHxd4ob/LnEd8UfMDDNk3b4tbXxmyC0dAB7nywx+H4tbiae3NHp2XMyKEsus4X99rdFbOO7SVj4502/1qUUhWuwfrm2WZhzmAooagL/OLfe9xmZlSWc4AyymrqzKdsIwem+BmdioA9bbRpvzeN6xonb6/NnFdoTG8Wjq3Pxj1uOFwCmDd/UP5CbY8tFXkQwCYqouuL4BhfCohLHqXt7VypT/pJart3EKY28RHfoDNxe7D4k8T80UpBDUErIlxZTSt9zjuTG5FlTHNxFu8N53Ir0ASR9VCkQ69sBS7pj3XasgDvumdnoIx/ldxijuU55u2HL7QNATusd7/hhWAx72kzcMbI3h6QvllJ0Lea4KQStSr5x0/wMb6hBZ+TnpKhSvnxRX2/pnAKwXxZ2isIxRBc2IgQ/ASifVRzkcRwVKaRdVr416bT3WA6LqV7httCcU3Dsi1TxaMDKmLT+ryy90CnKblyIunAraMVnIepsHb7xznp88F5R3mb33xXgrZnmwD7yQkYBhvHzOKC0TtFaGVX5k4O95sUzpOCSC78QTmXzfe7K8oFv8ARAyYB4rqU+Q==
    GF_AUTH_GITHUB_CLIENT_SECRET: AgAWWj40/Wp9zEK0yfKKGFy9vyqenjY2ADvJyVT08SOByVJ8sV9fzvn5/5dGaUXwLIM5lfbV4k5sEdSKwHgwQ4hIbsqydNH4xMKs9atknvPrlihSCkq6EWJeZIzOif31bNX9E5evZwI61FesdyutCEXJf0oJ9jtXuIHYDMSWfskbrxE4EV8AacuWPWwVVwpb6gKhtV7JtlGG3z1TqtDfXJXqJsYng7dxKNabBcKPYM6CVyeSQ4dQdc/RLtMkJCQwoSXwn2TYu6hMQ83NGmF8RqKtJM4/l6ERuEIuBT1714NBRQ4Rn2vkK1ibfpdJi87CFwjx0Or+4NkW6IZ6rmg9897SBRhPfULV7Zr9Zbf5uUormEYT/LmAJrEO0NjcYe1NMIU/FZiQdvfVFs3FDTSqobxPByoPLsDhqiUo0+ldMPangOmJJhCAHpixx139r9QmzGuNXHwqObLcyE6gT2t5+jN54tWumUT/m1QYr4LzQGQGgJUNQ7bDJNADJqVoAxB+v7xfABnOnrwvFlfE96K2jU0HYrUQ2JSVlKhrsV7HZSerxZIgjPb2lesiLnDr6gZwFl9t9nhnc5DD9zT02ovbH6XSyxL2OsTnwEp9oBuJnAN/qrwuESkPNNiib+avOSsjAnhXBrNmu1cAYA89/6otd9idWimSSJbK6SNA3cm5vbPaQU79yNfcfXterc7ARgDlMRleodyCu3M3Uw0Mt9g/RG2HLia9ZStHlkV0qr91MlnmNe0fUryHVHd0
  template:
    metadata:
      name: grafana-github
      namespace: monitoring
