---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: operator-oauth
  namespace: tailscale
spec:
  encryptedData:
    client_id: AgApcdkOQSTcmjLi9X0Acu8CiQBqVWuxpt73iswqkrgYZjGxMA55NaGrQvh+zCCLk6fj0jGtFFj9LEqykm5SOygn238ToSqVFoaHorcg+kb3sgLHarlnCmVkRHWecQaGbOK1hBqRYeV2k2kSXKBp07d9gIRVIOSdvMBo8YrA5tn1e75CSfWuWMJBmD6Dq3OjKZ/L+wCHIHmRbtwPWT4ucb4jSAOBrCToPWC7cKKBQviNtHduesC75X8pBh5M5uLPEk7/GEWkdiXkh8dz0DydGHFRB6P4y9DJNMqT0kbv+mBY3wdXPVTDVdU17rQRvXwhwY8aMmJgzoO2P5MIT2Vvtfast21cJWAp/qDu/FIra/sCC69k3kBTE1+M4BdIsgqxXvEk05WDsdthlFMueKavHLUuHFQTcApSvZdvVdqMSt/2Q4er29UX6OxH3cYkHR82gWdFHPW14aeDBG9ysJPKODm+gjfiqtT7oHbahvNYi+1WyhH5NId+fwTAVePjO6PfS2nmjkqf8uNLoMz7Z3sPfJN793fuUWzV5RcxD9b658PCurIlfURQ20Dvf+aYLcdyOCFz0AqySabVZLKMHcae1KiEV4VnmZAyPjzAg/F0aSeEpf2ZYSKz4IirkORFolaDKaMfo7I2Ov53+VT8hOZeI53K8HP+o9OiuasFsk/EaFX2SvyevJ+5AEi2HGm/KQLplqDOA6T4LrvddeTDz0ZFgj3f3g==
    client_secret: AgAvawBt2wGWCFyvmkzzbkAEXDGnTDUPUWtycKzZBX0VDWXfckhL+8jE/pjaIfiAl/Cz1AZwPfrLP8xter+P35DvUlhQ3pQNM5viaX3/kI+ZZaL/9ffnrmkDSwtvIHfTonKr+KCFLe7DsbC5Q+F4t4S6G4SpXgBaxul3e8bZXKzJFUQungK8MlNhFF7ARyIPjurI+gWBVORnLVxPOniUtM2JmsiZ1Y4GVj1CYw5x5vK2a1cKi0Rb3aHmi0XeqJsoAb6TTFSKy3ZiI8yvr0pdEZWbCiKFlvdYPJvUbQekRgWRRrpgUPmsKSbjku1sPOEPbRTEzWtesWarR/X7U5pDRUejO6HvsVbwpp6WJXx101YHdSdq+TDquyQydqyJcc/r/iKfuQqOQTK8S4+1hjoKl44HAYko9/khpzp3/p1emZERevj1IndCQEqtW6Cx6BV15kgQ46MN5w3Mhkv4CcfHxQnTeuRAt+Q8yOp/f8irTVrp1HYAeDZjVm6l8pTD0DaLr3sSu0Z6ZzETrTLfBY8WzPnXa7YjTL+ryG5OiJQP2198CMDfCaFj9gI4HqvmHEnvksH/5lQ5UOPTNVq+1beU1F+SPIAPmQv2dB+YXtkz+T/WPTGg/kw5xbVs/zn887bjQOZB5itcOLEKMk6guewd5f9kFnT4ZPF0PsqhlEhCR0sEXeewhZYkd84eddZjeM7yLIRw04n50oEea7JKUI+MbCj9FSbNV3fEayDHODus7mYrdhZU6swcPjhhkbzMN6BlAbmmN69+W+nr13o2fy7cG9KO
  template:
    metadata:
      name: operator-oauth
      namespace: tailscale
