apiVersion: v1
kind: Service
metadata:
  name: prometheus-external-service
  namespace: observability
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 30030
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: grafana