apiVersion: v1
kind: Service
metadata:
  name: grafana-external
  namespace: observability
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: {{ .Values.externalServices.grafana.nodePort }}
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: grafana
