apiVersion: v1
kind: Service
metadata:
  name: prometheus-external
  namespace: observability
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: {{ .Values.externalServices.prometheus.nodePort }}
    targetPort: 9090
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: prometheus
