apiVersion: v2
name: csi-driver-nfs
description: NFS CSI driver and the nfs-csi StorageClass backed by the NAS export /nfs/k8s
type: application
version: 0.1.0
dependencies:
  - name: csi-driver-nfs
    version: 4.13.4
    repository: https://raw.githubusercontent.com/kubernetes-csi/csi-driver-nfs/master/charts
