---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: csi-rbd-secret
  namespace: ceph-csi-rbd
spec:
  encryptedData:
    userID: AgBlMjBRiwHW1JrpcjbzgjljEqD+1KJ+3OTwzIO51+LHvO4eM03WOO91ulO7fOEiOR+EZE1+gqEyLkqo0A/Ss2nu63hDUJoFVsA7UYLV7lzQUvaP6gVpp6AFAM9J3ha5G1PKgIaiSRTFiZh2+mH2FEo0Jo0mpU/VRRWp6A4c1UtA6jFVxXHYW+ZZ9oIdx3sdWdK8Mco2aVLNykqOxfL7QKLg9IunvsrOMyKtrbtpHIyTGwmBe6ZEP1SXxSBCgb7MJ532fHJu2MG1Huyt0gtcxlvmj4868a2MDyEK23wTXHoZiJU93U5TtOWVb25+F9ltvHPBZftAT1JiLnCb93XTidTkOm4XzJqbx5CHBUNBt+2VQfnj8DYbtJlNIczXQm1KF0EQcikctMG6pGGdUSqb7wHMG0MD8xY1InTPi0V8mevBJ62t0k0V8sXowxBTDZGr/mrfVY9HwzbiSVq5lElBbOT/YDxU0+/qCQ6GoMiFt82b8lmj4w96kY+TnPOsxeahedwG1rLFZ6o1YZijmR4fIPFDgMmK9QpB7iCw6SLGFgccy1c/WpQqbppQ/Ukz3cG1fpvs0wGZAcLsvjeioMbBqgIWtDjuSenZMb2x4ngd7yE4yEdisY13xPGDySLEJmNh9Zn3zbIVoBhG2GIIhfsW/Bms0pupqgCxybRsQWnqbp/FyYgQd1VQoSzsDbKjtanSlB0AomU=
    userKey: AgB3NzkbzKaOUWXnCki3fdZxmjvjq5GcjECPeND1jZY3AT8kdYR1VxUdMW8rkzJyRBZ7+vNPvwruyxWc+3FKG3YWlV4ltWHjun0JEafcSjU8kUYNCnJoDEZjfUEbTdloS1yuUWaO12NRdhBLV3YOTKekWSaQC8KtFul0deUJa+aFmhF39/+VucmFAmLp2nj+tfcqrQ5HqyJRj9AscnW5CWQ8XguwUs1UqHDqp4mfbu3rVnRymJTcxPBzEohIqDMZLgY7E05ISJTQ0Euzu75ZMpXmADq66/UjLOJ8epMs3DIKixqm2N6ln9akxnuNnEeu+E2550VDDqt2hXyNO1XhL1nF1znyFKLwDwx+uov2BYTy7S5amNYaU2rcHuWBPWECrCjvnXI4HfnsQt0E3tzf7N8gSLleS+KESwa4ZEQGsK/Rv27Fsf2OyJ0Sap5rWFRPO5KBPD46EtplYcng56gfpJI2sN3IXaaswvRTsZvimxBYR+UfKMd5AigxkO6iKyAaVfBTqc2Fl6JkxXUZP931/aKeIukxWVi6FeRKXwP8M7pHku0zT2jetDD8/1A8HjXflE0rDlJrpTlsOEPGwZ6tu18BCPgqoEmsPUtJ5JMKjntxAPArkybBcYEMvEbSjwCjkYOsx+77KHt/qoQh/I3THv77F7F/7mD/GX7gxSraMKU0y0EiVFrxO1CR4ZkEfvrQU8rdRl61r4ZOhLjnxTZa14k1OwC2fm7FBw3Pdm8DpqpgtGvUkz5exrDlWz+GV0HvCqN+ITyLElAk6yCII8w=
  template:
    metadata:
      name: csi-rbd-secret
      namespace: ceph-csi-rbd
