apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-adapter
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: prometheus-adapter
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: prometheus-adapter
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
    helm:
      releaseName: prometheus-adapter-release
      valueFiles:
        - values.yaml

