{{- $cfg := index .Values.applications "tailscale" | default dict -}}
{{- $namespace := default "tailscale" $cfg.destinationNamespace -}}
{{- $syncOptions := default (list) $cfg.syncOptions -}}
{{- $hasSyncOptions := gt (len $syncOptions) 0 -}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tailscale
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: {{ $namespace }}
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: tailscale
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
    helm:
      releaseName: tailscale-operator
      valueFiles:
        - values.yaml
      version: v3
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
{{- if $hasSyncOptions }}
    syncOptions:
{{- range $syncOptions }}
    - {{ . }}
{{- end }}
{{- end }}
