---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-dex-github
  namespace: argocd
spec:
  encryptedData:
    clientID: AgBYaaLMm/R8aL4Mutc9xkMOha38Jv8pLzLS+ds/xq/L2eEN1pF0AWUn6hwGmwNX+RsAPqmJKrR53QPI6709OxdR8SXNJ93vzw567/Lt+J2QoDOF0B3ogas8Jk2F0ApJyaXV37S3fo36jRe8M+Rr7n3Kc6hnviBVlgOLJyYlk43d/xai7wtifE0ikaWg2BNvsMhFKyA68ml4CIfdOsIvrvu4+QRDwgsHJX6YXsBehe4l8WqT7La7x8czM81ecECwlgXwzvEp6BCE7JkR68qDxFKjyKTJovaNLP+sKcWXb6JPjBrlffJ3As5V07S4t1beTehApzsB1pJI/TohEjAn1HSHznVTBKghS7bqSU6kTGVJl+Wazh5lkRv/DyEFBIpkT3+EwFxAX/0U69M8k0kl9Yv7IxGpxF9L0DoaPm35nbmY/TZJk0w7sUYk2wvv8NlAZz86Zsmq8NIVtbSglz1/Ywhbr7o2aI+SGDwrCP0VkHTWsr7sBNXytMi9k5UEqWptmoO4qOZ4zTJyGlnpEcAI2RqjAV3aJ+1Yk3z/1Ffxe25NEApVIxidiwLlxeocmPsHCI7uUoX9aY4JRZB8VWMura1wynj4EoA0iNQeo1svcGny2iWsq0FCdJ2FqNB5+503pxVrZzE5EDVvoyrFQCM9pnYHjf4L7+mTcQeB0EBY8BDAeJKem+qYgZ+g+bB16ZYuP3x51vHBqX1EvVb+74wN1HwixWObr58=
    clientSecret: AgBRu2vj7AOkSFU014s2LX41svItzh5wwN04iQyOjcGCBVA1ylKbWFtZIHVVyhEo2dTwwyncPYbYRt5uESmgPgHwMGzvJnFV9XEAHKbpsy75cguPEjM1+4coUWSWhX/oxMw3uocVsWgfAA1ULVcJ1otDLyoBvug9VmlnW5xB/8rcKEPrreOBLPwwpCwSqile1WxV5EO2r4brj1r+SC3TXpWJfaWc9oOISC3tr6wVeP4pcuTiQOrNZzsmRXlmUpr4Vf78aOiURVoK/ES3tPh//Pn3Fnw+DSIDaME1y8ZNDPJxVpYyaKCUGClTS3oXaq0pMiw63GhrLEowohitG23UQ4lLstg9ZJtwaEP5NOFuXQ7gDz713XuHPDIfz4okTajWHbKVZKe81df5KR395Ln7qUNbztWD1Xnn7akOJelK9TrXJSCWr9mNqgMOYi9wlfZqPHDXMnSSFl6DFmUC3KFw3KUHtdC9x40//xx8seiJDpi5maidi/aVPgNMjTVO/HxEefJL/11dIoIknkYvXNvftsFimgukGXNRl/xuNLKxpcVAOyQEMM0Ez5/Tfqhq8fZOy/i1cmCiIfQb28+XXRd2tVzUpYaQhGqiSZcHN725RuCiYrBLYp9AQpdAyvOiObs1JhOTW+TT54JRJncFfC80rRpgxHg9KL+Pbe6cx4Q+CZUOvlw+OkuJqQqYlS/Hp3XshzLnoxJ1U/fkL9f7NPGBNiUkv+aZTXosixjDfGhG+56NrH50Go3cPXhK
  template:
    metadata:
      labels:
        app.kubernetes.io/part-of: argocd
      name: argocd-dex-github
      namespace: argocd
