---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: couchdb-admin
  namespace: obsidian-livesync
spec:
  encryptedData:
    password: AgATsAr4mEMBvCyDayNwx8BtvExKDDkorekPXvZ4Vdh6BBeH1fldeBkZFcKZ5c5ZBklQlU73byRka5Gi7m6ICFXHbgzSyvHnEx5hr7RJB5X3ApbKWtQ7mz2sUJwVRK34mh6xFkVUqiuGPNuMcD3omsPiDQSYf5jJCmd1y6WZIQpIDW1CfYzMmwztxqp1u2xas8oJcw/FYn1zRsGZ5eSYMS7R+BxC+OTXgH7cpGFkpqYPb5/g+KLPn7X74KXV3dBNmDkvxy50jxJzVc3ANU7Roak2Js6RpbPi+Enf4B+Jyt+owC+dzoj8u4/BXxldGEUqrtu9JYP2H4j0NZfkmGLL4RRYXhlm2yzK+yLSTbWmOz6KyC/9mWRVf2HVKenTK196HpO7z20o+fqKdO/5HwdYbHDECT3Rw5V2o0AetAvMjwu9Ut9tsBGrvaQwf/IE9F5lfmx5t1lmAQoMwO0UvYZvtf+scsPvtp7YqvBMRR5FqeXeN5qpCmK5HmhYZSYxmWBaCpU4AayfeKY41NgqjauNmKo61t8LlOSAnJx6l1N1yAeiAWH5FtOWq1TORM+6n6tUntcPfph7csQhYVMbd1nNCvt7nOhwQmtEZrnOucyRJ+HKIE3ccSH8qnJWF8rDvstyHN60CDZIFUU5SJ6f53+ty55bsJr4+YgKpLYfuSX6l6g3TEP4qGG6tuzKhJD4MxH2hXF2Ek+ktS8h7ongEbGF
    username: AgAbBlecBNVCSAz1oga7n3dIaYWea+RX5L8fAtfpNcACc2xjo0g9JC1SZA+jUnon/VvGBfiRuDWCKwxMlXWdl+VfdxqIlx0XrkkUR2t/0tYbimLL0rL+TlOxZq1BYdbvT6p0n0EcspdQ6CxfSr9uDPotiniH3a+DHtuOrYLLbJvHdROXLFeyFM1NnRc0UeHPl1yWZiTNMBi5AM8kkiC4j0G5iWa9BpmEoFR7d8SaGn/fydabR43W/HLoyoquRZOVTpZa6OFJAFIOs0JzHCYrSjT8VM6B2fMPo46PNhyP40MysdynpEqkb4NcOMPh/abBu0Jif7ufrw8fuXn3D+hWNmjBfJ4bsiPH1WbjulVO/3k5qaF2onFjlay/RwOsn6Zrjej2B1xsxxZ25s9EWYlMToQI3Ok/oASyUFNEfPQ9mzmJLqSKm+1L4Woo7FrVYuejZHT5gqa1578TwPLQWGNv0taA4GgO+j9H8byXZQCcvJs56DVRxtt1E4YgIAmA/JGvNZ/LeOlBA1Fn//3W4+PPZjoRdnA52HfN2NVUo4WlM0EiGbYK2Et9HuBvYBcAnewB1lUa8Mzu6ZlbtJzp+/WFa2d08qPZfocQkKkNy2AoWrrdaHog0qCl5BTLshWECpUDV265S+NnSeaIrYDN24gmmpRplpIvTikrle1Ll+WzJduUNvQD9f/3f6dOZRqILCK0/dL23bWkLQqeF4A=
  template:
    metadata:
      name: couchdb-admin
      namespace: obsidian-livesync
