
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres-operator
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: prometheus-community
    # targetRevision: 
    helm:
      releaseName: prometheus-adapter
      valueFiles:
      - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: prometheus-adapter
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
