---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tailscale-secret
  namespace: tailscale
spec:
  encryptedData:
    client_id: AgB3EFx1dBB4TyL5P9EnAbP6ZQLRaRgOZsNpP6quTae9qcnLeNCFdJ8Q3B5wcBLXebbF7I+O+bF1R9qV02DmcvtaUayaaJs0mdENgxQhsyso5NF9vulXBn7rIp/uyzr4b7Vxb6uEiFwVkvMn4FBX4u28QEhN8RwXKHX5b+i2IdSfdSbJ54qbU45W035auqKTnVqIYQ85qMbaVe0lcVqtGEhFk78igX0489/67lwiqRorLi73tSh+j8XWrjE9CraixC3Tg+YIALXb9uHLpuuxrb4TI+Hu96fpNXNLHIrjkke9Qp5K4ursYcGsnQnIccU9NupVB0DLfO4t9Qu1X0UWo+SMPHn0IfIIP5Jxe3W38KbkHalNJ8qN2kcf0rWPXMtrimqoYDM1XFUnmcuwFXBylWQW0jVYIiN52/eKvj4ZyAZBpbmJ0m7fDf7aIWg0+oZcTeqFRFTZxAgmP8KGZ4191Jo1QBe2PGlk8xvu/FeX1WXnBy2FW4HVAoJyp5VnpJ6CoLMLB9d9yE5bI+DnE3PPR6V6oYhW+V4hXOXT4w6BQhl+G+0VIti9Qz2kJy4k8IqCJ5aTk2zha1Zi0BVQ7LKg+cVqcS5SW4T/3uKG98YZo8vPYMEpX5s45UmqRMkRPwU9KrOpB0Cnh+BjaPsZnLwIuXxEDA3cL6tqFSiMQFE7WRW0gP0eVxheaan5/PIu2Py1v5dqM7VYdEqQJ807NaSayeo7ug==
    client_secret: AgBhWiw44lYxPPxIz6/5WMhKcj/nEpkojq9hzIyQKimG02ox4hjwNprmqG52E1lfWT1J4s/AFo3tF7xXJ2+p8C4SKuMtnPTOR1DPWMGFs+PZRRrtx+XSUyMEmhflGE/j0Y0s38/PiKa7mNhJkanN0F3cZEhU3spHMmWM/adDGqKz5MaDuS3ZoA3EiyouT/Bs03huLApQotkZ4yxeKhWNwERPjZjAd0QoGjD/DlQOzz7bfKOTXytZ76WE5onCnfbTbMH5ZbEVvqLsdKa1FUHgi/EJTxty2/Kvu1qJrelFSrjnZGYV1zmuXJT0v31MTelIHPAXGP8c9idfAQxrINRAsNyVVAPDHk5MK4CRANejZTk053Wxday72GcxQN4U6vYWhjB6mbuYCL6S5RW53W6fpvPNZ0KR9HbBBUqjB5JMS1oDZN7eRRtPyIoO+XdXABcLVstbrGbn2kB9eF9YTF4WvPy9uQs2BFonliXO4zV5/TZw4JX44CQdv6YMUbgFSTHhwEmYjARfvtWSgCE/4qo7bRY39wXFWBgxM/JkdmtSIGNgj3yubsAq6/53MVdBSBQJitq+ZK11TPiaGWBehR6W8RBfjT85nGdP6bgQtZmdK6uAsHFLilPSA4CTwxG9lpqczj5FTS3jXC7mlZV4Ireri+lBBaaPxMozBNIz1kNz4hQ7BUEzvpno+idrcEpX3eSRd5a9JV5Tsv3yg1fZZv4LGJtfS6F/8CIobcn+s2intN5/JUip5FIjT448aythQBj3rRDrUxdk8IVoqa8OJUOJ40CC
  template:
    metadata:
      creationTimestamp: null
      name: tailscale-secret
      namespace: tailscale
  syncPolicy:
      syncOptions:
      - CreateNamespace=true
