---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: operator-oauth
  namespace: tailscale
spec:
  encryptedData:
    client_id: AgCpt6DwrpYL8ZEo6TBiEc7hamhjtXZ7vK24cIvvoxSbGkRSphErgJ/IN/h86KFWH5xqGE7F4lPUTIvqD9Be+RUrzEs1D2WJZl4UU9WCzve9rrJGQJ5/aKoKxrOFVu1lsCJvWxLLfsDL8Onj79tz7QUexIVuTxcwZC4vMpTPB72e1YpBzMgwJs5/kaxj6sluEPxiszJ710gF2wdyegdUMt7JrWWD1HlmuH6SZm9zYUctifW6oBJOgWhYjSKAtU/679qqQU4yqxtaiQmNaXa6PyGT2/z45kxXhZGNuFui0aoKni6aCL2Oqf08VQyTNpI73e+QnV6a83+Eo/VA4qRcsT0Y0tjFBTbYjviMt2WttOoGCcCYhU/Xs21OTDbHnhCgMynYdLzhOIhssWY064Bh6n3oIcWA3IZhkY4dQjRsKYgBaM5gpvLcO/dAS8Utf83L2dZMfswz6NZmQfwgRIYzptoW4p92IETH/dF0hYTjgf42w0YgYpJhTmNb4cYmv2GgEJj3H/pCX1npqL3wJgwoH6Ek0tXtp4kwa3cA0mxYuJIqGOQ0zkvX2NmkEK972ireKGnaS4KmME5uSgKdI80AWBnFW3zGnkFrJ+gFs8LxlRCR7cEob9LpqYT9qNylNZM1T6RzHdJxUUqXPPMKFwHYFqOiWQp/u7cN+jtmtqr7Krl/dNYT14BtnKkba+z9n5WoCP5zdhXBtD/JD2MZ6pw5ooUOKA==
    client_secret: AgANYGUVDi61/UjpkvHQHDJwUP4FV7/WxmGs7Ay7Ni713NOq7lVP9MGpRKN413QDoQyZmoo5V9wRq/47Rt/p0zX/o7MDN0Qvs03gY07P4Kir6hV/nSxYUTmRvujzXqenVuydbw/kwsDaNswqpqNGV3yy8UHhs1s1jy5SBOBg3Zg5dUEq0t8wHKdnqUfrdpRxpfF6iNEtuNNogHKx24NKgv5k2qIx9YEOHDlTbSnPh/OFg1MtWnGpgeAs+BbQ0iQBaIJeraeW3mvCcrCxhtR+A4FqZeEx6+XdjJKBw53IYAwXi4tDXfEP9VcGpKRKXS7D2j4H5MC8eSr4QH/SLZDueuw0uOFBAPhEw7ThdnPFS856kTEq+AkcT6ZgfnSVDR09C/nF2/uVesKgoaZ7mi4mRtrTMKqTXf7ODJxyMb0ihyqxGIYrfZJMWHADVCMy3Zr1ZdhDPx0X1aYg/zzlSna8kJhsvmqW23AUyAzL31UOUcKVvvigeO+4d74Ouz3hS0fUkutGH8wkdLjqp98OnQN4FmLg/WsPE3LHOOQLqrDRNjV0ZQAku0byhaBdUXHJb59jd8YLth9XQ7BTVjvhM+w+sb4AHIxkMCkGWJtPfxegYm07HowpUh+5H65RGtT1i7T2W0jaDzqPm4BWWzkxsxVm9PHB9pdfHqWVc9AKyczy2lg8l2kGUoxCBqQTV4SdAzzYQMBfd4mxnoxVBiUIWsEZA98MDfmIVLPCXkHmHaek10XfJ8+P1IqLLxoJQB/fYeywtPyspzlsIjmbTSVd+vIQgQBr
  template:
    metadata:
      creationTimestamp: null
      name: operator-oauth
      namespace: tailscale
