---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tailscale
  namespace: tailscale
spec:
  encryptedData:
    client_id: AgBQUdWvC1TSDzhOyiqDbC/8BDVhbRox5a+0/eL0/n0Uy2heQ7NnCOcW7kPhQi+wSDaeOLBTEMh/lRRf5f7I9Q1CRLtNVCFRfUNuf7t6tDtXwUEuew2p2rKozvLHPxHfum6v7lv67zKH96kbitIuEt7ne5NRSCPLXSRVIGupAtehxOQCOj9BanKHekaZeRuH8EvLhCD7a9bduXBrqrF/S7oDjIrll1jUIU3DO9vdgxf7EsgE/3kgxgTGKj5l6jWoD4r90GFDaQKMIY/6byYaA/zeIA4Ue1j5YnSc5FNvaldJt/fMZQMn9n8+h3b+khwxLskuJCeJQNKzE0l3k3B1sMBZ9myQDGz2t02tPbsQUeYx4mIGydOTCiWiVUgiMCvCzNV4OQKMEmmIQOJJ3qmlSj/g8xtgf7a2a7sBv6Fy4n/7zwYnXZZaZ+AbUxedtHisrKyTkCQMLcfdlR49Oh4jGaSEX8xkZ0TxdEXWx9ITbJg71xhh4iR/Xc5+p8MASCTDmc+4MslxiVls+fbbmIHKGZoYamZRsjCewTmV3+ekUB3d1TdGdtMCe9riNKHxuTI14wYc8ME8rHr2Ip/s4DXn6W44aADeyB6A6aHEfNRj8DEwEdcBxhxCwo4sKOB99trIMFvaQJXuvyG6ku8w07J6eNFrQLuKInVzeUG8MkIfCiYcLKosIUDhaEyG++fM/WTrWwo0UAuL2jOKhbetuUuLsfW5lw==
    client_secret: AgCpAbWY0mnJrwFE5iIqmtAhBn6F+4S3zjCyF4nyOC+igjRlSc6vRN+vjpDnRa4+94D3I+Q1J6YgvN6xdOTolKtGVYA+WA78d+Sbmy2WkvAp9fmNAcgxRyTtG3qHqaXKRCs0WkvhGtnWG/fL2UyH2RgJBRh1/v43Y/UPoyRjIbLb70FO+KDM80LSESNBIDRGTBP6gc5j48WvpBpUi6CSPGM/4JR27KEJB4pLXSL190f0uVgBSbvOzasy6SEBDkDWAc+UqpVR2SJQ95BjQMtW6woWdUdrBqbmuawTFQToRdqJHZslWMUcQKLw0Z8M9ypFFtjWgUDbTjIEWqYUCLdd/NgJTcOqJAoMyFF8BkxPZ25OkRAMnFxHbUQPJHN9q9AbwQsZbF8MctwB0oJiJA0TcYAt+4HJrWswSKkKlUew9NzILnkPVxqFCqejrRRYTXm4uTwnrIDOH7mdEm+DjJyQlFF9DjZ7rBDGtu+2bQSmmlXalPUuYFeS9jnG/zEwtLw8nya/Qmbq7zjp7ISHZrluOtnTBrDMlL/jpxMhRebpPcM2fftGI7vUcHyeru5qu/NnWgPte1Fzi+sI6u5FQzdmUP6kYR9gw31t7gEkuqsmfzEUa7zKeQOcaK4U+sPGXypEdZOk0+RRy9mkmXmnWJGZ77aHkJ1Cytg1pF0b96/RNq8X7qiwPq7wBU7lnhmP9IjLkQuCMpUgnplUxeHp8iF9V6FYfZUbfioSxBTpAynr286w04Gipq1moE2c6WW7+bBd71vs4rXrY4qunwGkIL1/zZdR
  template:
    metadata:
      creationTimestamp: null
      name: tailscale
      namespace: tailscale
