---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: operator-oauth
  namespace: tailscale
spec:
  encryptedData:
    client_id: AgAx3++fgph0lzAEempuK1UCW7yjgtmaf0Iw41TSKUV9rGDF1sq9h8M1NJ31wSUdOnKNeWJMzkkC2UOa6Vfb7oVYWAlDu9DeatdeS/numYBiCeaFGe2hgZP5/I6zAe+jCHykO4gyOvENqrE1K3PDT7pkWekpJKHsui+aNUmA/O/YUnQlzkrtpeDAlJbDzAL0GsJd9TpAl5lcfVKT53xly41NZO+/3LT/DHYjmTXFAXEiZyyNioO+qj5hr3AnZfQtqJ3q5CYJx60u+TyWzvHdM+W5553QOQ+evyXD6pPHhDlazRY8VY8+g0z6ccorrNv/v1ilcTL+2L/wWTWdXB3DS5pOjUNrs11DXgqVrkbKwd61hksiznIGyR+jgQ4hUonSANCqBp7PokmTN6ZvPAMQUgboFjmO5MrjFMGfbZpQEgn3PmBBrsL44Pws1SkMn+HxwUey4sZZ3deyaM2Fb5VmX02jY7GbV8DyQH800exm1GxXCFblcOsycYgZ71EJLNHPGwunYL5tYNhTF7IjTUNRcinYQXL/mIPDClZ3UBc8muCY2AHhO7nba+KymvF8yH7hWFL5ThaKAzeNaA6ePneem+dlvkCQ3+gi/3aC6M4fCMn/F4iDTII21VE43dIfu6a0Y+vGO7IhEuVb5iEpBeU/fou7PUdz9AQ7FgLrdMLGV/sWX0CbQjQCjtySftVKlEHZMTQgLrifJX5UrbIkH6ogXjZ7+A==
    client_secret: AgBpz016rUyuVSJw1tCL3IDbSXmOnWp2iEx3ty+W9/b5E0jKbDsQgyQOsEiaQvZ2xzL1XKSqljNIWorlKSFz8FqE8YAQOTrIEKnRlQ0TVxn8GPknWAzLxw7YmbnTwwtTHFck+qafWovCfQqyHm9bp7ZyQ37O30/aItJdbIBkIL2T1qZHiF+Jb5KlaRAzzUe/wRWeVE6W/PdG0klGTp6FnCtAvtP8iP8QWljbIbdRcbrrrOphWMtdcO4iw3mhuLnBsm7ciCwbs9CCZ7vcpryvZ7n1AMG+Sp8Ck0wHgKt/TeAv9SkM/CeGI/WRI71q+1F93Wsn+oeov3bts55sgJwL4nDJRP2kTpknbNyENNOgYlFJLa1D6zQGPN2/RDCYjkqEb9/Bd97/IBxbGaHzKrBcAMR8oQEpRbYRLVexvKhirbnIP6ZsskSLBdmqT6sh8JXMbn2xn7pYnQ5ha8U5mwcqtIvA/2NsFWtj9yOb6YOOViaROX19yhGvUqD2OhvR2K4NXaRdNpHs0Glp+Cuer9qfQFgxwKaRpRlybpnezFDNd3zt2qQqrLQQ0hNCOP3krMkAl3A3OKAGCwynvn4vWW/unlR2P/Q1VdMB/T1hF9AHq1d8sclFclGJHKTNLIx9Oe/Ps+0KHz3clhK/H3Wpsg3PuvJU7EIdGLFo0KEmVn1XNiWiR+NhKEHWRJRt8dLRqhSgjY0JJserhujWh+apl0KMOjaUv8DY73uoHjL51vFpPDoU+1WC+lZwjnDBLdhkjO0DEl5mieb1hoxWem+iZMLScvNx
  template:
    metadata:
      creationTimestamp: null
      name: operator-oauth
      namespace: tailscale
