kind: "postgresql"
apiVersion: "acid.zalan.do/v1"

metadata:
  name: {{ .Values.cluster.name | quote }}
  namespace: {{ .Values.cluster.namespace | quote }}
  labels:
    team: {{ .Values.cluster.teamId }}

spec:
  teamId: {{ .Values.cluster.teamId | quote }}
  postgresql:
    version: {{ .Values.cluster.postgresql.version | quote }}
  numberOfInstances: {{ .Values.cluster.numberOfInstances }}
  {{- if .Values.cluster.maintenanceWindows }}
  maintenanceWindows:
  {{- range .Values.cluster.maintenanceWindows }}
    - {{ . }}
  {{- end }}
  {{- end }}
  volume:
    size: {{ .Values.cluster.volume.size | quote }}
    storageClass: {{ .Values.cluster.volume.storageClass | quote }}
  users:
  {{- range $user, $databases := .Values.cluster.users }}
    {{ $user }}: {{ toJson $databases }}
  {{- end }}
  databases:
  {{- range $db, $owner := .Values.cluster.databases }}
    {{ $db }}: {{ $owner }}
  {{- end }}
  {{- if .Values.cluster.allowedSourceRanges }}
  allowedSourceRanges:
  {{- range .Values.cluster.allowedSourceRanges }}
    - {{ . }}
  {{- end }}
  {{- end }}
  resources:
    requests:
      cpu: {{ .Values.cluster.resources.requests.cpu }}
      memory: {{ .Values.cluster.resources.requests.memory }}
    limits:
      cpu: {{ .Values.cluster.resources.limits.cpu }}
      memory: {{ .Values.cluster.resources.limits.memory }}
