---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflared-credentials
  namespace: public-gateway
spec:
  encryptedData:
    credentials.json: AgCzuo19d2jJVifzCp+0VJFw/quR3roH11lw5ov3OqluMwt9Qqeguabsoqdo0wPgByvaCum25JBKc7t0E/GfXspQ7QfVPXzxNo0XkG8L9jJTWH2jee/SW2AvXOEhmclJWGeqarhoaGzCe4kczypx7AzUiBjOZhT9zINeAYjf7fwnKy7SmfUiKCTJ6rNWrEb2HMHybKPAFz+P5T4mavUS7utnuHvnBEkwljsrfhACW49t+c1EY3AkzFsG1C8Oj9PS6sEJngCr1iCPIzy2YP52sgTZqmiza+WGzfHjTW6zdmrmcBzUe6tI3sZYzAwMPpfOihzoO+9JkeN26BsvLokqWxFYiG6gGO6TRpYv5xJ+fBdGZHCfnRiLQn/y4riGV040pV5xwhLO0awD+lNxM3FxLEh+NP0CduAeQUveOKqPo/O36lz9NUCdwSYUu2FsZNCmPcZ11Rq3H/8MIrgVU/5BPvbL9onCCIg9Ugjypg8pv7CDH/KX+PF6Q7KqzlBGM5UR2tgI5nyvmoV5ygrIxuMucICGp8sAxygIQFWF1o057KRTn+VRudORMFqaU177O2amGdyAFQEK8p6NdifwgFvY9cP3ZhSj8foPuGvlSCQVFe7/p5cVvcUFH9Tql//RfEH3dQgdWnlyrA4JFZase8eTmur3ADwsgndiiQC6TNdiJlhiLr84GkXgZEArAAc9tiu/RGAzi83CmmranCWkQy4GWLWpmLSzeOr/oGBZ5DsbZjKILBqGRspNCzFxlwp5EhHcWEQY8WSRwVnC3hb095E15vNkt3LHFYj5rB8tX/+rYvfH05+ggLLUhVvIR+cSEpBoqxLDLUtdpsiGLBhsbzoHfjAmLHmFQlqbbJsPYj0DGEQo2p32Okcruli63y6RH4CbAOSs9lWu9CW0mxGbxmfESkvc5JfBcy82qyOq7smPKsLT
  template:
    metadata:
      name: cloudflared-credentials
      namespace: public-gateway
