---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: vaultwarden-admin
  namespace: vaultwarden
spec:
  encryptedData:
    token: AgBepQDttne0/Yv7ASVkUWcBr+CQ5ivyb4rVN16abhrU3jvmcHcnOP7wAMx8+K50QzCrG+vluofRCM4/iLNZZ+W15k6lhotTkiEc/mhR+VV+rLTH7x4+gGfPQ4wT4cH4pteBMnexF5RZVcNrKOwsKxnlti8km3UQ29igU4YUSsPPyWBMY0EBnEpAUpibS0ihqJCNn2ISPrMN5ZctP5J+MJ/PHxD1akGNxLPX+4MnELp5YOneLC/CGc/mHPDxUbuVBGqa0rd2T/wai6f/Mbnt+3IwLVDTHoeNdtxth04lswnUepOLVaXrqHb104BrAb7RvNI+gp5ZLEDU1tugnZiNSJ9OEL7hCdPWtJYRpXz3TF5WhZRKNIBg49i737ytfJQ9oiB+zRascbg/mKsplEGD+/uTHZsdraCNm1+mIOEVqE6KO1Y/Esk3Mdl7Nug5vpx+k3r4V4OiftvPum9vnf/o58/kxeaEDOgxZW3XN3vQyMlUl6kFFD2a0sWT6RKfAzn1hocLresIBFlY9sdTooPdGbFRlp5JTztGsEIsTan7mBWR6A7lGJHKJwnN9VgkyzofmYZHhgo1liafiQvuD/6x3V46NK0iQ8gyhTMNSOth4e1ktSrQjfFhKcSUT9jt0UygsVh10Y6sjR3igIbTA713whZx/ab6sh9ZnMw4X6XXIyv3XeI2JBMX2FjAkmG51J94z7andzcqAdyW5x+IYa3voJNr7Rh6Y8tdJVixhIprty6RFRrPbNH4jLlGxw9OI6+WBgJwvH+zrvy2dQgN96P62U9CbWs7WJHdXJtIWBeBw0LgPxUDO1MX7TZD4olOFCPDzKPRJ4j7HwgPvXme8kK/fNPgBkSU+T65
  template:
    metadata:
      name: vaultwarden-admin
      namespace: vaultwarden
