---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: vaultwarden-admin
  namespace: vaultwarden
spec:
  encryptedData:
    token: AgAFMJ5YrXGp5kggW6J+WOdjLH3IEeuQmj8z6IpUfDNWuaOAovmlMc8OYZ+Umt+iDp9YR+G6Zs0Q0VFWnAH+0BJ6PbvgA7CUxZoTuxZ9TofTnR+Y07rb+8LNcQVN/Wea12G0PoK5ZUV12mIaLt57owl/lWR0nEKq+eKNFq+dzJKRlK6DZFNdQbuewr95oWms2E7V5XxUaPvu0Jvf78Njs5/tbV/v+ZJktVEahIzX3VRcxJDWyLqgnGW4J9RR501pE3ACrbF2NrRoTTx4JNjZSCUUebn+e2PxynnJsPFk+dCR6gcrMyhfehDP9LZd36s6t1zxBP0g6MtGU6k7xwL8ugGXSuRZOdjq5fv0+7sG6QStrUA+xTCaWIPNpLUhuy5HWTCLQjPe4/V1oeby+P37iWhdlyRCyJe2Bq7bL0yWxbiOxODred9FIIhH7mGS7G427kd9tDmnUD4jpTSzqFzCSp3ULQTCsXaspF+JNyrg4f6VzX8t9wjp2tiWLIgTENOJfiqUQ9Jj6yy12gljGz5ygWKnGDChxr5gLtN74ukNlDaLNaXL6oGFQrOrams1E/jL56o6rz5YamepDUb0bOxYakbqI4nOUFcxJQSYNiUGpXUkjebc36ywbIyW/FyxGTZVU9WZVi1pYDgDxIe+jqjx+sWF8E9MeCaU5hEnkzFk3hcP63T5COMKppTLtqXpIDkKTdle0NUH4I/J+ps0flV/bj0j60slcbyujJNiTWExoEhHAKOLGPE/l4usiSL20iPctQHpevGJjJQSUYhX+SqnmqhfqWARnXCHrCkPR0okuug185W1FC+JvOpxicvLtuoC2m/pziHX1hJZruuKbmEd6iaHVwMmIAqD
  template:
    metadata:
      name: vaultwarden-admin
      namespace: vaultwarden
